spring.application.name=todo-app

# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/todoapp
spring.datasource.username=fjara
spring.datasource.password=

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true